name: ci

on:
  push:
  pull_request:

jobs:
  analyze:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: template
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: dart analyze lib test

  format:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: template
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: dart format --output=none --set-exit-if-changed .

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: template
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter test
