#!/usr/bin/env ruby
# frozen_string_literal: true

# Apply instance.config.yaml → dart_defines / Secrets.xcconfig / key.properties / .env
# Usage:
#   ruby apply_instance_config.rb [instance_root]
# Default instance_root = cwd.

require "yaml"
require "json"
require "fileutils"
require "base64"

root = File.expand_path(ARGV.fetch(0, Dir.pwd))
config_path = File.join(root, "instance.config.yaml")
example_path = File.join(root, "instance.config.yaml.example")

unless File.file?(config_path)
  if File.file?(example_path)
    FileUtils.cp(example_path, config_path)
    warn "Created #{config_path} from example. Fill it, then re-run this script."
    exit 1
  end
  abort "Missing #{config_path} (and no .example). Copy from App 模板 template/."
end

cfg = YAML.safe_load(File.read(config_path), aliases: true)
abort "Invalid YAML: #{config_path}" unless cfg.is_a?(Hash)

def dig(hash, *keys, default: nil)
  cur = hash
  keys.each do |k|
    return default unless cur.is_a?(Hash)
    cur = cur[k.to_s] || cur[k.to_sym]
  end
  cur.nil? || cur == "" ? default : cur
end

project = dig(cfg, "project", default: {})
identity = dig(cfg, "identity", default: {})
platforms = dig(cfg, "platforms", default: {})
ios = dig(platforms, "ios", default: {})
android = dig(platforms, "android", default: {})
runtime = dig(cfg, "runtime", default: {})
branding = dig(cfg, "branding", default: {})
umeng = dig(cfg, "umeng", default: {})
store = dig(cfg, "store", default: {})
signing = dig(cfg, "signing", default: {})
signing_ios = dig(signing, "ios", default: {})
signing_android = dig(signing, "android", default: {})
deploy = dig(cfg, "deploy", default: {})
asc = dig(deploy, "app_store_connect", default: {})
play = dig(deploy, "play_store", default: {})

display_name = dig(project, "display_name", default: "App Template")
app_id = dig(identity, "app_id", default: "app_template_local")
app_id_dev = dig(identity, "app_id_dev", default: "#{app_id}_dev")
firebase = dig(runtime, "firebase_configured", default: false)
firebase_s = (firebase == true || firebase.to_s == "true") ? "true" : "false"
ops_url = dig(runtime, "ops_console_base_url", default: "")
slogan = dig(branding, "slogan", default: "Ship faster with a solid foundation.")
splash_min_ms = dig(branding, "splash_min_ms", default: 800).to_i
logo_asset = dig(branding, "logo_asset", default: "assets/branding/logo.png")
copyright = dig(branding, "copyright", default: "© 2026 Your Company")
onboarding_version = dig(branding, "onboarding_version", default: "1")
umeng_android = dig(umeng, "android_app_key", default: "")
umeng_ios = dig(umeng, "ios_app_key", default: "")
umeng_channel = dig(umeng, "channel", default: "Flutter")
ios_store_url = dig(store, "ios_url", default: "")
android_store_url = dig(store, "android_url", default: "")
bundle_id = dig(ios, "bundle_id", default: "com.example.appTemplate")
team_id = dig(ios, "team_id", default: "")
apple_id = dig(ios, "apple_id", default: "")
application_id = dig(android, "application_id", default: "com.example.app_template")

def write_json!(path, hash)
  File.write(path, JSON.pretty_generate(hash) + "\n")
  puts "wrote #{path}"
end

write_json!(
  File.join(root, "dart_defines.dev.json"),
  {
    "APP_VARIANT" => "dev",
    "APP_INSTANCE_ID" => app_id_dev,
    "APP_INSTANCE_NAME" => "#{display_name} Dev",
    "FIREBASE_CONFIGURED" => firebase_s,
    "OPS_CONSOLE_BASE_URL" => ops_url.to_s,
    "APP_SLOGAN" => slogan.to_s,
    "APP_SPLASH_MIN_MS" => splash_min_ms.to_s,
    "APP_LOGO_ASSET" => logo_asset.to_s,
    "APP_COPYRIGHT" => copyright.to_s,
    "APP_ONBOARDING_VERSION" => onboarding_version.to_s,
    "UMENG_ANDROID_APP_KEY" => umeng_android.to_s,
    "UMENG_IOS_APP_KEY" => umeng_ios.to_s,
    "UMENG_CHANNEL" => umeng_channel.to_s,
    "IOS_STORE_URL" => ios_store_url.to_s,
    "ANDROID_STORE_URL" => android_store_url.to_s
  }
)

write_json!(
  File.join(root, "dart_defines.prod.json"),
  {
    "APP_VARIANT" => "prod",
    "APP_INSTANCE_ID" => app_id,
    "APP_INSTANCE_NAME" => display_name,
    "FIREBASE_CONFIGURED" => firebase_s,
    "OPS_CONSOLE_BASE_URL" => ops_url.to_s,
    "APP_SLOGAN" => slogan.to_s,
    "APP_SPLASH_MIN_MS" => splash_min_ms.to_s,
    "APP_LOGO_ASSET" => logo_asset.to_s,
    "APP_COPYRIGHT" => copyright.to_s,
    "APP_ONBOARDING_VERSION" => onboarding_version.to_s,
    "UMENG_ANDROID_APP_KEY" => umeng_android.to_s,
    "UMENG_IOS_APP_KEY" => umeng_ios.to_s,
    "UMENG_CHANNEL" => umeng_channel.to_s,
    "IOS_STORE_URL" => ios_store_url.to_s,
    "ANDROID_STORE_URL" => android_store_url.to_s
  }
)

# iOS Secrets.xcconfig
secrets_dir = File.join(root, "ios", "Flutter")
FileUtils.mkdir_p(secrets_dir)
secrets_path = File.join(secrets_dir, "Secrets.xcconfig")
File.write(
  secrets_path,
  <<~XC
    // Generated by apply_instance_config.rb — edit instance.config.yaml instead.
    DEVELOPMENT_TEAM = #{team_id}
  XC
)
puts "wrote #{secrets_path}"

# Android key.properties
keystore_path = dig(signing_android, "keystore_path", default: "android/upload-keystore.jks")
# key.properties is under android/; storeFile is relative to android/app/
store_file_for_gradle =
  if keystore_path.start_with?("/")
    keystore_path
  else
    # instance-relative → path from android/app/
    rel = keystore_path.sub(%r{\Aandroid/}, "")
    "../#{rel}"
  end

key_props = File.join(root, "android", "key.properties")
FileUtils.mkdir_p(File.dirname(key_props))
File.write(
  key_props,
  <<~PROPS
    storePassword=#{dig(signing_android, "store_password", default: "")}
    keyPassword=#{dig(signing_android, "key_password", default: dig(signing_android, "store_password", default: ""))}
    keyAlias=#{dig(signing_android, "key_alias", default: "upload")}
    storeFile=#{store_file_for_gradle}
  PROPS
)
puts "wrote #{key_props}"

# ASC API key content for .env
asc_key = dig(asc, "key_base64", default: "")
key_path = dig(asc, "key_path", default: "")
if asc_key.to_s.empty? && !key_path.to_s.empty?
  abs = File.expand_path(key_path, root)
  if File.file?(abs)
    asc_key = Base64.strict_encode64(File.read(abs))
  else
    warn "ASC key_path not found: #{abs}"
  end
end

play_json = dig(play, "json_key_path", default: "play-store-key.json")
play_json_abs = File.expand_path(play_json, root)

env_path = File.join(root, ".env")
File.write(
  env_path,
  <<~ENV
    # Generated by apply_instance_config.rb — edit instance.config.yaml instead.
    APP_IDENTIFIER=#{bundle_id}
    ANDROID_PACKAGE_NAME=#{application_id}
    APPLE_ID=#{apple_id}
    APPLE_TEAM_ID=#{team_id}
    APP_STORE_CONNECT_API_KEY_KEY_ID=#{dig(asc, "key_id", default: "")}
    APP_STORE_CONNECT_API_KEY_ISSUER_ID=#{dig(asc, "issuer_id", default: "")}
    APP_STORE_CONNECT_API_KEY_KEY=#{asc_key}
    MATCH_GIT_URL=#{dig(signing_ios, "match_git_url", default: "")}
    MATCH_PASSWORD=#{dig(signing_ios, "match_password", default: "")}
    MATCH_GIT_BASIC_AUTHORIZATION=#{dig(signing_ios, "match_git_basic_authorization", default: "")}
    PLAY_STORE_JSON_KEY_PATH=#{play_json_abs}
  ENV
)
puts "wrote #{env_path}"

# Symlink / copy .env into platform fastlane dirs (fastlane loads local .env)
%w[ios/fastlane android/fastlane].each do |rel|
  dir = File.join(root, rel)
  next unless File.directory?(dir)

  dest = File.join(dir, ".env")
  FileUtils.rm_f(dest)
  begin
    File.symlink(File.join("..", "..", ".env"), dest)
  rescue NotImplementedError, Errno::EPERM
    FileUtils.cp(env_path, dest)
  end
  puts "linked #{dest}"
end

puts "Done. Run: flutter run --flavor dev --dart-define-from-file=dart_defines.dev.json"
puts "Release: cd ios && bundle exec fastlane beta"
